In [ ]:
pip list

In [129]:
import numpy as np # 넘파이를 사용할 때 np라는 이름으로 많이 사용(관례)

# numpy로 2차원 배열 만들기
a = np.array([[2, 3], [5, 2]])
print(a)
print(type(a))

# 이중화 리스트 만들기
a = [[2, 3], [5, 2]]
print(a)
print(type(a))


[[2 3]
 [5 2]]
<class 'numpy.ndarray'>
[[2, 3], [5, 2]]
<class 'list'>


In [ ]:
# 넘파이 배열 슬라이싱 하기 -> 리스트 슬라이싱과 같음
d = np.array([[1,2,3,4,5], [2,4,5,6,7], [5,7,8,9,9]])
print(d[0][1]) # 2
print(d[1:, 3:]) # 2행과 3열까지의 모든 배열을 가져온다.

In [ ]:
# 배열의 크기 알아내는 shape
d = np.array([2, 3, 4, 5, 6])
print(d.shape)  # (5,)
e = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
print(e.shape)  # (2, 4)
f = np.array([[0.1, 0.2, 0.3], [.2, .3, .4]])
print(f.shape)  # (2, 3)

In [ ]:
# 배열의 원소 유형 확인하는 dtype
print(d.dtype)
print(e.dtype)
print(f.dtype)


In [ ]:
# 배열의 유형 바꾸는 astype함수
data = np.arange(1, 5)  # 1 ~ 4 까지 이루어지는 배열 생성
print(data)
print(data.dtype)
print(data.astype('float64'))  # 기존 int32로 된 원소들을 float64 타입으로 변경
print(data.astype('int32'))  # 기존 int32로 된 원소들을 float64 타입으로 변경


In [138]:
# 0으로 이뤄진 배열 만드는 zeros함수
h = np.zeros((2, 10))   # 2 * 10 배열의 0으로 채워진다
print(h)


[[0. 0. 0.]
 [0. 0. 0.]]


In [134]:
# 1로 이뤄진 배열 만드는 ones함수
h = np.ones((2, 10))   # 2 * 10 배열의 1으로 채워진다
print(h)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [131]:
# 연속형 정수 생성하는 arrange함수
np.arange(2, 10) # 2 ~ 9 까지 이루어지는 배열 생성

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 행과 열을 바꿔주는 transpose함수
a = np.ones((2, 3))
print(a)    # 2 x 3
b = np.transpose(a)
print(b)    # 3 x 2

In [ ]:
# 배열의 사칙연산(+, - , *, /)
# 1. 배열의 크기가 같은 경우
arr1 = np.array([[2, 3, 4], [6, 7, 8]])
arr2 = np.array([[12, 23, 14], [36, 47, 58]])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 - arr2)
print(arr1 / arr2)


In [133]:
# 2. 배열의 차원이 다른 경우 
arr3 = np.array([100, 200, 300]) # 1차원 배열
print(arr1 + arr3)  # 브로드캐스팅 되는 경우 == [[2, 3, 4], [6,7,8]] + [[100, 200, 300], [100, 200, 300]]

# 브로드캐스팅이 안되는 경우
# arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 1차원 배열(10개의 열)
# print(arr1 + arr4)

arr5 = np.array([[9], [3]]) # 2차원 배열(2x1)
# arr1은 2차원 2x3 배열
print(arr1 + arr5)  # [[2, 3, 4], [6,7,8]] + [[9], [3]]


[[102 203 304]
 [106 207 308]]
[[11 12 13]
 [ 9 10 11]]


In [137]:
d_list = [[1, 2, 3, 4], [2, 3, 4 ,5], [3, 4, 5, 6]]
# d_list 2행부터 전부 0으로 초기화
# d_list[:2] = 0    # 리스트 자료형에서 0으로 쉽게 대입 불가능
d = np.array(d_list)
d[:2] = 0
print(d)

[[0 0 0 0]
 [0 0 0 0]
 [3 4 5 6]]


In [ ]:
# 설문지 데이터(quest.csv) 전처리하기
import os, usecsv
import numpy as np

print(os.getcwd())
os.chdir(r'd:\min\python-data-analysis1\20240627')

quest_csv = usecsv.opencsv('quest.csv') # quest.csv파일 read
print(type(quest_csv))          # list
print(type(quest_csv[0][0]))    # str

quest_csv = usecsv.switch(quest_csv)
print(type(quest_csv[0][0]))    # float

quest_np = np.array(quest_csv)  # numpy객체로 변경
print(quest_np)

print(quest_np > 5)             # 넘파이 객체의 원소에서 5보다 큰 원소들의 값은 True로 변경하고 아니면 False
print(quest_np[quest_np > 5])   # quest_up의 인덱싱을 활용해서 5보다 큰 수만 가져오기

# quest_np2 = quest_np > 5
# print(quest_np[quest_np2])

quest_np[quest_np > 5] = 5     # quest_up보다 큰 값들은 5로 세팅
print(quest_np)

# csv파일로 output 하기
usecsv.writecsv('quest_resultcsv.csv', quest_np)

In [ ]:
discount = .05  # 할인율 5%
cashflow = 100  # 단위는 억

In [ ]:
# 현재가치 구하는 함수 
def prsent_value(n):        # n은 연차(총 사업기간(년))
    return cashflow / ((1+discount) ** n)

In [ ]:
print(prsent_value(1))
print(prsent_value(2))

In [ ]:
# 놀이공원 사업의 사업성 분석(필요 패키지는 numpy_financial)
!pip install numpy_financial

In [ ]:
loss = [-750]           # 단위는 억
profit = [100] * 10     # 단위는 억
print(profit)

cf = loss + profit  # 리스트끼리 '+' 는 insert or append개념
print(cf)

cashflow = np.array(cf)

import numpy_financial as npf   # 순현재가치와 내부수익률 함수를 사용하기 위한 파이썬 패키지 로드

# npf.npv(할인률, 현금흐름) -> 순현재가치(npv)
# npf.irr(현금흐름) -> 내부수익률(irr)

# 여기서 할인률은 4.5%으로 가정하고 계산
npv = npf.npv(0.045, cashflow)
irr = npf.irr(cashflow)

print(npv)  # 순현재가치는 41.3억원
print(irr)  # 내부수익률 5.6%


In [ ]:
# 판다스(pandas)의 데이터프레임 사용하기
import pandas as pd

pandas = {
    'name' : ['Mark', 'Jane', 'Chris', 'Ryan'],
    'age' : [33, 32, 44, 42],
    'score' : [91.3, 83.4, 77.5, 87.7]
}

df = pd.DataFrame(pandas)
df

In [ ]:
# 판다스 데이터 프레임 사용 함수들
# (1) sum함수   -> 합계 구하기
print(df.sum())
# (1) meang함수 -> 평균 구하기
print(df.mean(numeric_only=True))  # 'name' 속성은 mean함수에서 제외

In [ ]:
print(df.age)       # age의 데이터 출력
print(df['age'], df['score'])    # age, score의 데이터 출력

In [ ]:
# 아파트 실거래가 데이터들을 판다스 데이터프레임으로 처리 및 분석하기
import pandas as pd
import re

# 판다스로 csv파일 불러오기
df = pd.read_csv('apt2308.csv', thousands=',', encoding='utf-8')  # thousands는 구분자
len(df)  # 데이터 행의 개수
print(df)

In [ ]:
# 데이터 프레임에서 앞의 5개의 행을 표시하기(만약 숫자를 넣게되면 숫자 개수만큼 출력)
print(df.head()) #print(df.head(10))
# 데이터 프레임에서 뒤의 5개의 행을 표시하기(만약 숫자를 넣게되면 숫자 개수만큼 출력)
print(df.tail()) #print(df.tail(10))

In [92]:
df.시군구
df['시군구']

0        강원특별자치도 강릉시 견소동
1        강원특별자치도 강릉시 견소동
2        강원특별자치도 강릉시 견소동
3        강원특별자치도 강릉시 견소동
4        강원특별자치도 강릉시 견소동
              ...       
26504       충청북도 충주시 호암동
26505       충청북도 충주시 호암동
26506       충청북도 충주시 호암동
26507       충청북도 충주시 호암동
26508       충청북도 충주시 호암동
Name: 시군구, Length: 26509, dtype: object

In [98]:
# 판다스 데이터 프레임에서 조건별로 출력하기
# 전용면적 값이 80이상인 것만 출력
# print(df['전용면적'] > 80)

# 전용면적 값이 80이상인 것만의 데이터 프레임 출력
# print(df[df['전용면적'] > 80])

# 전용면적 값이 80이상인 것만의 단지명만 출력
print(df['단지명'][df['전용면적'] > 80])

# 복한적인 조건으로 원하는 데이터 출력하기(면적이 130m2가 넘고(and) 가격은 3억원 미만인 것만 출력)
print(df['단지명'][(df['전용면적'] > 130) & (df['거래금액'] < 30000)])

# 복한적인 조건으로 원하는 데이터 출력하기(면적이 130m2가 넘거나(or) 가격은 3억원 미만인 것만 출력)
print(df['단지명'][(df['전용면적'] > 130) | (df['거래금액'] < 30000)])


1                 송정한신
4         송정해변신도브래뉴아파트
5         송정해변신도브래뉴아파트
6          강릉교동롯데캐슬1단지
7          강릉교동롯데캐슬2단지
             ...      
26502    충주호암두진하트리움아파트
26505    충주호암두진하트리움아파트
26506             호반현대
26507       호암리버빌(2단지)
26508          호암힐데스하임
Name: 단지명, Length: 12306, dtype: object
140       현대5차
256       레이크뷰
370      라이프타운
392       현대3차
407         두산
         ...  
25655       건영
25657       건영
25840       신라
25891     세원홍실
26016       동아
Name: 단지명, Length: 74, dtype: object
0                 송정한신
2                 송정한신
3         송정해변신도브래뉴아파트
4         송정해변신도브래뉴아파트
6          강릉교동롯데캐슬1단지
             ...      
26499               진도
26500               진도
26503    충주호암두진하트리움아파트
26506             호반현대
26507       호암리버빌(2단지)
Name: 단지명, Length: 14054, dtype: object


In [108]:
# 판다스 데이터 프레임으로 원하는 자료만 가져오기
# 앞에서부터 시작해서 11개의 행 데이터와 '단지명','거래금액' 2개의 속성값만 가져오기
# print(df.loc[:10, ['단지명', '거래금액']])

# 전체 데이터에서 10억원 초과하는 가격으로 거래된 아파트만 가져오기
df.loc[:, ['단지명', '거래금액']][df['거래금액'] > 100000]

단지명    거래금액
1191            DMC디에트르한강  129000
1192           DMC한강에일린의뜰  130000
1193           DMC한강에일린의뜰  115000
1446             일산요진와이시티  155000
1449             일산요진와이시티  102000
...                   ...     ...
20912         송도센트럴파크푸르지오  101000
20913        송도아메리칸타운아이파크  121000
20933          송도자이하버뷰2단지  160000
24887  천안 불당 지웰시티푸르지오 2단지  105000
24895            천안불당지웰더샵  110000

[1229 rows x 2 columns]

In [107]:
# 판다스 데이터 프레임에 속성값 추가하기
df['단가'] = df['거래금액'] / df['전용면적']
df.loc[:10, ['거래금액', '전용면적', '단가']]


거래금액      전용면적          단가
0   23000   59.8000  384.615385
1   31000   84.9450  364.942021
2   16400   43.3800  378.054403
3   24500   59.9900  408.401400
4   28500   84.9900  335.333569
5   32500   84.9900  382.397929
6   60000  163.9852  365.886678
7   37500   84.9855  441.251743
8   35400   66.0388  536.048505
9   31000   66.0388  469.421007
10  27500   59.8400  459.558824

In [113]:
# 판다스 데이터 프레임으로 정렬하기(sort_values함수)

# 거래금액 오름차순으로 정렬
# df.sort_values(by = '거래금액').loc[:, ('거래금액', '시군구')]

# 거래금액 내림차순으로 정렬
# df.sort_values(by = '거래금액', ascending=False).loc[:, ('거래금액', '시군구')]

# 4억원이 넘는 아파트 중에 전용 면적이 넓어지는 순서(오름차순)
df[df['거래금액'] > 40000].sort_values(by='전용면적').loc[:, ('거래금액', '전용면적', '시군구')]

거래금액      전용면적              시군구
17949   51000   25.6500    서울특별시 송파구 문정동
17992   93000   27.6800    서울특별시 송파구 잠실동
17646   50500   28.8500    서울특별시 서초구 서초동
18280   47600   30.1355  서울특별시 영등포구 영등포동
18281   44000   30.2372  서울특별시 영등포구 영등포동
...       ...       ...              ...
16297  670000  244.2240    서울특별시 강남구 도곡동
16292  745000  244.6600    서울특별시 강남구 도곡동
14988  200000  244.8647     부산광역시 남구 용호동
17619  650000  244.9720    서울특별시 서초구 반포동
17638  262000  257.1200    서울특별시 서초구 방배동

[8711 rows x 3 columns]

In [116]:
# 판다스 데이터 프레임에서 원하는 문자열만 찾아서(str.contains함수) 핸들링 하기
# df.head

# 시군구 컬럼에서 '강릉' 이라는 단어가 포함된 데이터 행만 가져오기
# df[df['시군구'].str.contains('강릉')]

# 위의 데이터 중에서 거래금액 평균값을 가져오기
df[df['시군구'].str.contains('강릉')].거래금액.mean()


21161.257575757576

In [120]:
import os, re
import pandas as pd

print(os.getcwd())
os.chdir(r'd:\\min\\python-data-analysis1\\20240627')

df2 = pd.read_csv('survey.csv')

d:\min\python-data-analysis1\20240627


sex  income  English  jobSatisfaction  stress
0    m    3000      500                5       5
1    f    4000      600                4       4
2    f    5000      700                3       2
3    m    6000      800                2       2
4    m    4000      700                2       5
5    m    3000      600                1       5
6    m    3000      500                3       1
7    m    5000      500                3       2
8    f    4999      600                4       3
9    f    5000      700                5       4
10   m    3000      500                5       5
11   m    4000      600                4       4
12   m    5000      700                3       2
13   m    6000      800                2       5
14   f    4000      700                2       4
15   f    3000      600                1       2
16   m    3000      500                3       2
17   m    5000      500                3       5
18   m    4999      600                4       5
19   m    5000      500                3       1
20   f    4999      600                4       2
21   f    5000      700                5       3
22   f    3000      500                5       4

In [127]:
# df2.describe()
# df2.income.describe()
df2['income'].describe()    # 기초통계량 보기
df2['income'].sum()         # 합계 보기
df2['income'].median()         # 중앙(중간) 값 보기


4999.0

In [128]:
# 기초 통계 중에서 빈도(frequency) 분석하기
df2['sex'].value_counts()


sex
m    14
f     9
Name: count, dtype: int64

In [ ]:
# 판다스 데이터 프레임에서 두 집단을 나누는 함수(groupby())
# 성별로 평균을 구하는 코드
print(df2.groupby('sex').mean())
# 성별로 합계을 구하는 코드
print(df2.groupby('sex').sum())

In [1]:
import matplotlib.pyplot as plt
x = [1,4,9,16,25]

In [ ]:
data = {'Barton LLC': 109438.50,
        'Frami, Hills and Schmidt': 103569.59,
        'Fritsch, Russel and Anderson': 112214.71,
        'Jerde-Hilpert': 112591.43,
        'Keeling LLC': 100934.30,
        'Koepp Ltd': 103660.54,
        'Kulas Inc': 137351.96,
        'Trantow-Barrows': 123381.38,
        'White-Trantow': 135841.99,
        'Will LLC': 104437.60}
group_data = list(data.values())
group_names = list(data.keys())
group_mean = np.mean(group_data)

fig, ax = plt.subplots()
ax.barh(group_names, group_data)

In [15]:
for i in range(1, 11) : 
	if i % 2 == 0 : 
	    pass
	else : 
	    print(i)



1
3
5
7
9
